### ISSUE TITLE
Do you want to add the JS portion of this to the helpers library?

### ISSUE THREAD

**Issue by mikemaccana** [anza-xyz/solana-rpc-client-extensions#3]
Foundation DevRel, Anza, Turbin3, Unboxed Software and StarAtlas have an [npm module](https://github.com/solana-developers/helpers) with [bunch of commonly requested features](https://github.com/solana-developers/helpers?tab=readme-ov-file#what-can-i-do-with-this-module). Can get `getStakeActivation()` in there?

**Comment by joncinque** [comment]
I don't think that's the best option, unfortunately. Although the package is currently only doing one thing, I imagine that we'll need more bits of code like this to replicate RPC work on the client-side in the future. For example, `jsonParsed` encoding should be client-side work, but RPC currently does it. If that functionality no longer exists in RPC, we'll need a place to host that logic, which could be in a library like this. Once we add more stuff, we can create a new package for all of that logic. What do you think?

Separate note: in my opinion, the "helpers" package has lots of great utilities, but it would be better to separate it into more logical parts rather than bundle everything in one place. For example, there are loads of keypair-specific interactions that could live in a keypairs module. For smaller bits, like creating a mint with metadata, that could be upstreamed or hosted separately as an example for people to copy and paste.

**Comment by mikemaccana** [comment]
Thanks @joncinque ! Making a separate package for client-side  RPC-ish functionality sounds good.

> Separate note: in my opinion, the "helpers" package has lots of great utilities, but it would be better to separate it into more logical parts rather than bundle everything in one place.

Immediately it's OK as the dependencies for these functions are pretty similar. They functions will be separated into individual files in the next release (thanks @heyAyushh !)

As new helpers with wider dependencies get added, a larger module that depends on web3 (probably v2), plus other smaller packages (each with their own more specific dependencies) would work well. People can import:

 - The large package ('batteries included') with it's dependencies. Someone what just wants a SOL-funded account easily can get that without wandering what they need to install to get it.
 - Individual smaller packages with their own specific dependencies to avoid unnecessary bloat.  
 
We generally want to avoid copy paste - copy pasted code gets out of date quickly and doesn't have distribution for bugs and security fixes.

**Comment by joncinque** [comment]
This will be published separately in the end, closing
